######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 4 12:32:55 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
QT -= gui

# Input
HEADERS += QUnixSocket.h Server.h Client.h
SOURCES += main.cpp QUnixSocket.cpp Server.cpp Client.cpp
